apiVersion: v1
appVersion: "1.0"
description: Demo gradually migrate traffic from one version of a microservice to another
name: istio-demo-bookinfo
version: 0.1.0
icon: https://mir-s3-cdn-cf.behance.net/project_modules/disp/c039b824474525.56334ce736de9.jpg
